[env]
CURRENT_DIR = { script = ["pwd"] }
SCHEMA="${CURRENT_DIR}/../schema/schema.sql"

[tasks.generate]
script_runner = "@shell"
script = '''
NAME=$(mktemp -u db.XXXXXXXX)
sqlite3 "${NAME}" < "${SCHEMA}"
sea-orm-cli migrate init -u "sqlite://${NAME}" -d .
rm "${NAME}"
'''
