[package]
name = "resippies-com"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
axum = "0.6.1"
axum-macros = "0.3.0"
tower = "0.4.13"
serde = "1.0.152"
tera = "1.17.1"
futures = "0.3.25"
tracing = "0.1.37"
mime_guess = "2.0.4"
include_dir = "0.7.3"
http = "0.2.8"
pwhash = "1.0.0"
regex = "1.7.0"
lazy_static = "1.4.0"
dotenvy = "0.15.6"
dotenvy_macro = "0.15.1"

[dependencies.axum-login]
version = "0.4.1"
features = ["sqlite"]

[dependencies.axum-template]
version = "0.11.0"
features = ["tera"]

[dependencies.sqlx]
version = "0.6.2"
default-features = false
features = ["runtime-tokio-rustls", "sqlite", "offline", "migrate", "macros"]

[dependencies.tokio]
version = "1.23.0"
features = ["full"]

[dependencies.hyper]
version = "1.0.0-rc.1"
features = ["full"]

[dependencies.rand]
version = "0.8.5"
features = ["min_const_gen"]

[dependencies.tracing-subscriber]
version = "0.3.16"
features = ["env-filter"]

[dependencies.tower-http]
version = "0.3.5"
features = ["trace"]

[dependencies.uuid]
version = "1.2.2"
features = ["v7", "std"]
