[package]
name = "resippies-com"
version = "0.1.0"
edition = "2021"

[build-dependencies]
base64 = "0.21.0"

[build-dependencies.rand]
version = "0.8.5"
features = ["min_const_gen"]

[dependencies]
anyhow = "1.0.71"
axum = "0.6.18"
axum-macros = "0.3.7"
base64 = "0.21.0"
tower = "0.4.13"
serde = "1.0.161"
tera = "1.18.1"
futures = "0.3.28"
tracing = "0.1.37"
mime_guess = "2.0.4"
include_dir = "0.7.3"
http = "0.2.9"
pwhash = "1.0.0"
regex = "1.8.1"
lazy_static = "1.4.0"
dotenvy = "0.15.7"
dotenvy_macro = "0.15.7"
axum-extra = { version = "0.7.4", features = ["form"] }

[dependencies.axum-login]
version = "0.5.0"
features = ["sqlite"]

[dependencies.axum-template]
version = "0.16.0"
features = ["tera"]

[dependencies.sqlx]
version = "0.6.3"
default-features = false
features = [
    "runtime-tokio-rustls",
    "sqlite",
    "offline",
    "migrate",
    "macros",
    "chrono",
    "time",
]

[dependencies.tokio]
version = "1.28.0"
features = ["full"]

[dependencies.hyper]
version = "0.14.26"
features = ["full"]

[dependencies.rand]
version = "0.8.5"
features = ["min_const_gen"]

[dependencies.tracing-subscriber]
version = "0.3.17"
features = ["env-filter"]

[dependencies.tower-http]
version = "0.4.0"
features = ["trace"]

[dependencies.uuid]
version = "1.3.2"
features = ["v7", "std"]
