DROP TABLE recipes_ingredients;
DROP TABLE recipes_steps;
DROP TABLE cookbooks_recipes;
DROP TABLE cookbooks;
DROP TABLE steps;
DROP TABLE ingredients;
DROP TABLE items;
DROP TABLE recipes;
DROP TABLE identities;