//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "cookbooks_contributors"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub cookbook: String,
    pub contributor: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Cookbook,
    Contributor,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Cookbook,
    Contributor,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Cookbooks,
    Identities,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Cookbook => ColumnType::String(None).def(),
            Self::Contributor => ColumnType::String(None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Cookbooks => Entity::belongs_to(super::cookbooks::Entity)
                .from(Column::Cookbook)
                .to(super::cookbooks::Column::Id)
                .into(),
            Self::Identities => Entity::belongs_to(super::identities::Entity)
                .from(Column::Contributor)
                .to(super::identities::Column::Id)
                .into(),
        }
    }
}

impl Related<super::cookbooks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cookbooks.def()
    }
}

impl Related<super::identities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Identities.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
