//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod cookbooks;
pub mod cookbooks_contributors;
pub mod cookbooks_recipes;
pub mod identities;
pub mod ingredients;
pub mod items;
pub mod recipes;
pub mod recipes_contributors;
pub mod recipes_ingredients;
pub mod recipes_steps;
pub mod steps;
