//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::cookbooks::Entity as Cookbooks;
pub use super::cookbooks_contributors::Entity as CookbooksContributors;
pub use super::cookbooks_recipes::Entity as CookbooksRecipes;
pub use super::identities::Entity as Identities;
pub use super::ingredients::Entity as Ingredients;
pub use super::items::Entity as Items;
pub use super::recipes::Entity as Recipes;
pub use super::recipes_contributors::Entity as RecipesContributors;
pub use super::recipes_ingredients::Entity as RecipesIngredients;
pub use super::recipes_steps::Entity as RecipesSteps;
pub use super::steps::Entity as Steps;
