//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use async_trait::async_trait;
use chrono::Utc;
use sea_orm::{entity::prelude::*, Set};
use serde::{Deserialize, Serialize};
use util::uuid;

use crate::{visibility::Visibility, Id};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cookbook")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Id,
    pub author: Id,
    pub name: String,
    pub description: String,
    pub visibility: Visibility,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::Author",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::recipe::Entity> for Entity {
    fn to() -> RelationDef {
        super::cookbook_recipe::Relation::Recipe.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cookbook_recipe::Relation::Cookbook.def().rev())
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::cookbook_contributor::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cookbook_contributor::Relation::Cookbook.def().rev())
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: Set(uuid()),
            ..ActiveModelTrait::default()
        }
    }

    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if insert {
            self.created_at = Set(Utc::now());
            self.updated_at = Set(Utc::now());
        } else {
            self.updated_at = Set(Utc::now());
        }

        Ok(self)
    }
}
