//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::prelude::Uuid;

pub mod prelude;

pub mod cookbook;
pub mod cookbook_contributor;
pub mod cookbook_recipe;
pub mod ingredient;
pub mod recipe;
pub mod recipe_contributor;
pub mod role;
pub mod step;
pub mod theme;
pub mod user;
pub mod visibility;

pub type Id = Uuid;
